spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_spring_mvc
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
#   afficher sql
    show-sql: true
    properties:
      hibernate:
#       formatter le sql generer
        format_sql: true

server:
  port: 8080
